# Generated by Django 4.2.6 on 2023-10-18 08:02

from django.db import migrations, models
import recurrence.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventRecurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255)),
                ("recurrence", recurrence.fields.RecurrenceField()),
            ],
        ),
    ]
